orders/urls.py
from django.urls import path

from orders.views import OrderCreate, OrderDetail, OrderList, OrderPay

app_name = 'orders'

urlpatterns = [
    path('', OrderCreate.as_view(), name='create'),
    path('pay/<int:order_id>/', OrderPay.as_view(), name='pay'),
    path('detail/<int:order_id>/', OrderDetail.as_view(), name='detail'),
    path('list/', OrderList.as_view(), name='list'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # keep admin first
    path('admin/', admin.site.urls),

    # other apps
    path('', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.contrib.auth import get_user_model
from django.db import models

from products.models import Variation
from products.views import MoneyMixin


class Order(models.Model, MoneyMixin):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE,
        related_name='orders'
    )
    total = models.FloatField()
    total_items = models.PositiveIntegerField(default=0)
    status = models.CharField(
        max_length=100, default='P',
        choices=(
            ('P', 'Pending'),
            ('A', 'Approved'),
            ('R', 'Rejected'),
            ('S', 'Shipped'),
            ('D', 'Delivered'),
            ('C', 'Cancelled'),
            ('F', 'Finished')
        )
    )

    def get_price(self):
        return self.to_money(self.total)

    def __str__(self):
        return f'Order {self.id}'


class OrderItem(models.Model, MoneyMixin):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Variation, on_delete=models.CASCADE)
    price = models.FloatField()
    quantity = models.PositiveIntegerField(default=1)
    image = models.CharField(max_length=1000, null=True, blank=True)

    def get_price(self):
        return self.to_money(self.price)

    def __str__(self) -> str:
        return f'Item {self.id} of order {self.order.id}'

orders/views.py
from typing import Any

from django.contrib import messages
from django.db.models.query import QuerySet
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import DetailView, ListView, View

from orders.models import Order, OrderItem
from products.models import Variation
from products.views import CartMixin


class OrderCreate(View, CartMixin):
    def get(self, *args, **kwargs):
        cart = self.request.session.get('cart')

        if not self.request.user.is_authenticated:
            return redirect(self.request, 'profiles:create')

        if not cart:
            return redirect(self.request, 'products:list')

        cart_product_ids = [v for v in cart.keys() if v != 'total']

        products_variation = Variation.objects.select_related('product').filter(id__in=cart_product_ids)

        for var in products_variation:
            stock = var.stock
            var_id = str(var.id)
            quantity = cart[var_id]['quantity']

            if quantity > stock:
                cart[var_id]['quantity'] = stock

        _, cart_total_price, cart_total_itens = self.get_cart_calc(cart)
        self.request.session.save()

        order = Order(
            user=self.request.user,
            total=cart_total_price,
            total_items=cart_total_itens,
            status='Pending'
        )
        order.save()

        OrderItem.objects.bulk_create(
            [
                OrderItem(
                    order=order,
                    product=products_variation.filter(id=var['id']).first(),
                    price=var['price_promo'] if var['price_promo'] else var['price'],
                    quantity=var['quantity'],
                    image=var['image']
                ) for var in cart.values() if isinstance(var, dict)
            ]
        )

        del self.request.session['cart']
        self.request.session.save()
        messages.success(self.request, 'Pedido criado com sucesso')
        return redirect(reverse('orders:pay', kwargs={'order_id': order.pk}))


class OrderMixin(View):
    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return super().dispatch(self.request, *args, **kwargs)
        return redirect('profiles:create')

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs


class OrderPay(OrderMixin, DetailView):
    template_name = 'order_pay.html'
    model = Order
    context_object_name = 'order'
    pk_url_kwarg = 'order_id'


class OrderDetail(OrderMixin, DetailView):
    template_name = 'order_detail.html'
    model = Order
    context_object_name = 'order'
    pk_url_kwarg = 'order_id'


class OrderList(OrderMixin, ListView):
    model = Order
    template_name = 'order_list.html'
    context_object_name = 'orders'
    paginate_by = 10

orders/templates/order.html
<div class="row">
  <div class="col">
      <h3>{{ pedido }}</h3>

      <div class="row mt-4">
          <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
          <div class="col-lg-4">{{ order.id }}</div>
          <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
          <div class="col-lg-4">{{ order.get_price }}</div>

          <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
          <div class="col-lg-4">{{ order.total_items }}</div>
          <div class="col-lg-2 font-weight-bold">Status:</div>
          <div class="col-lg-4">{{ order.get_status_display }}</div>
      </div>

      <div class="row mt-4">
          <div class="col">
              <h3>Produtos</h3>
          </div>
      </div>

      <div class="table-responsive mt-3">
          <table class="table">
              <tr>
                  <th class="d-none d-lg-block">Imagem</th>
                  <th>Produto</th>
                  <th>V.</th>
                  <th>QTD.</th>
                  <th>Total</th>
              </tr>

              {% for item in order.items.all %}
              <tr>
                  <td class="d-none d-lg-block">
                      <img class="cart-img" src="{{ item.image }}">
                  </td>
                  <td>{{ item.product }}</td>
                  <td>{{ item.variacao }}</td>
                  <td>{{ item.quantity }}</td>
                  <td>{{ item.get_price }}</td>
              </tr>
              {% endfor %}

          </table>
      </div>
  </div>
</div>

orders/templates/order_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'order.html' %}
{% endblock %}

orders/templates/order_list.html
{% extends "base.html" %}
{% block content %}
<div class="row flex-grow-1">
  <div class="col">
      <h3 class="mb-4">Pedidos de {{ user }}</h3>
      <p>Abaixo todos os seus pedidos realizados na loja.</p>

      <div class="table-responsive">
          <table class="table table-striped">
              <tr>
                  <th scope="col">Pedido</th>
                  <th scope="col">Total</th>
                  <th scope="col">Qtd. Itens</th>
                  <th scope="col">Status</th>
                  <th scope="col">Mais detalhes</th>
              </tr>


              {% for order in orders %}
              <tr>
                  <th scope="row">{{ order }}</td>
                  <td>{{ order.get_price }}</td>
                  <td>{{ order.total_items }}</td>
                  <td>{{ order.get_status_display }}</td>
                  <td>
                      <a href="{% url 'orders:detail' order.pk  %}">
                          Ver <i class="fas fa-search-plus ml-2"></i>
                      </a>
                  </td>
              </tr>
              {% endfor %}
          </table>
      </div>
  </div>
</div>

{% endblock content %}

orders/templates/order_pay.html
{% extends 'base.html' %}
{% load static %}

{% comment %} {% block titulo %}Pagamento | {% endblock %} {% endcomment %}

{% block content %}
<div class="row">
    <div class="col">
        <h3>Escolha o método de pagamento</h3>
        <p>Para o desenvolvedor: adicione seu método de pagamento preferido.</p>
    </div>
</div>

{% include 'order.html' %}

<div class="row mt-4">
    <div class="col">
        <a href="#" class="btn btn-primary btn-block btn-lg">Pagar</a>
    </div>
</div>

{% endblock %}