orders/urls.py
from django.urls import path

from orders.views import OrderCreate, OrderDetail, OrderList, OrderPay

app_name = 'orders'

urlpatterns = [
    path('', OrderCreate.as_view(), name='create'),
    path('pay/<int:order_id>/', OrderPay.as_view(), name='pay'),
    path('detail/<int:order_id>/', OrderDetail.as_view(), name='detail'),
    path('list/', OrderList.as_view(), name='list'),
]

products/urls.py
from django.urls import path

from products.views import (ProductCart, ProductCartAdd, ProductCartRemove,
                            ProductCartResume, ProductDetail, ProductList)

app_name = 'products'

urlpatterns = [
    path('', ProductList.as_view(), name='list'),
    path('<slug>', ProductDetail.as_view(), name='detail'),
    path('cart/', ProductCart.as_view(), name='cart'),
    path('cart/add/', ProductCartAdd.as_view(), name='cart-add'),
    path('cart/remove/', ProductCartRemove.as_view(), name='cart-remove'),
    path('cart/resume/', ProductCartResume.as_view(), name='cart-resume'),
]

profiles/urls.py
from django.urls import path

from profiles.views import ProfileCreate, ProfileLogin, ProfileLogout

app_name = 'profiles'

urlpatterns = [
    path('', ProfileCreate.as_view(), name='create'),
    path('login/', ProfileLogin.as_view(), name='login'),
    path('logout/', ProfileLogout.as_view(), name='logout'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # keep admin first
    path('admin/', admin.site.urls),

    # other apps
    path('', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_cart.html
<div class="table-responsive">
  <table class="table">
    <tr>
      <th class="d-none d-lg-block">Imagem</th>
      <th>Produto</th>
      <th>Var.</th>
      <th>Qtd.</th>
      <th>Valor unit.</th>
      <th>Total</th>
    </tr>
    
    {% for product in products %}
    <tr>
      <td class="d-none d-lg-block">
        <img class="cart-img" src="{{product.image}}" />
      </td>
      <td>
        <a href="{% url "products:detail" product.slug %}">{{product.name}}</a>
        <a class="ml-3" href="{% url "products:cart-remove" %}?vid={{ product.id }}">
          <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
        </a>
      </td>
      <td>{{ product.variation}}</td>
      <td>{{ product.quantity }}</td>
      {% if product.total_promo %}
      <td>{{ product.price_promo }}</td>
      <td>{{ product.total_promo }}</td>
      {% else %}
      <td>{{ product.price }}</td>
      <td>{{ product.total }}</td>
      {% endif %}
    </tr>
    {% endfor %}
  </table>
</div>

templates/partials/_footer.html
{% load static %}

<footer class="container-fluid bg-primary">
  <div class="container text-light">
    <div class="row">
      <div class="col">
        <div class="p-1">
          <span class="align-middle p-1">Feito com Django</span>
        </div>
      </div>
      <div class="col">
        <div class="p-1 text-right">
          <span class="align-middle p-1">Por Diego Marcelino</span>
        </div>
      </div>
    </div>
  </div>
</footer>

<script src="{% static '/js/jquery-3.2.1.slim.min.js'%}"></script>
<script src="{% static '/js/popper.min.js'%}"></script>
<script src="{% static '/js/bootstrap.min.js'%}"></script>
<script defer src="{% static '/font-awesome/js/all.js'%}"></script>
<script src="{% static '/js/custom.js'%}"></script>

templates/partials/_head.html
{% load static %}

<meta charset="utf-8" />
<meta
  name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>

<link rel="stylesheet" href="{% static '/css/custom.css'%}" />
<link rel="stylesheet" href="{% static '/css/bootstrap.css'%}" />

templates/partials/_messages.html
{% if messages %}
<br />
{% for message in messages %}
<div class="alert mb-5 {{ message.tags }}" role="alert">{{ message }}</div>
{% endfor %} {% endif %}

templates/partials/_nav.html
{% comment %} {% load omfilters %} {% endcomment %}

<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
  <a class="navbar-brand" href="{% url 'products:list' %}">E-commerce</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Conta
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'orders:list' %}"
            >Meus pedidos</a
          >
          <a class="dropdown-item" href="{% url 'profiles:create' %}"
            >Atualizar meus dados</a
          >
          <a class="dropdown-item" href="{% url 'profiles:logout' %}">Sair</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profiles:create' %}">Entrar</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profiles:create' %}">Criar conta</a>
      </li>
      {% endif %} 
      {% if request.session.cart and request.session.cart.total > 0 %}
      <li class="nav-item">
        <a
          class="nav-link nav-cart-link active"
          href="{% url 'products:cart' %}"
        >
          <span class="nav-cart-text mr-1"> Carrinho </span>
          <span class="nav-cart-count mr-1">
            <strong>{{ request.session.cart.total }}x</strong>
          </span>
          <span class="nav-cart-icon mr-2">
            <i class="fas fa-shopping-cart"></i>
          </span>
        </a>
      </li>
      {% endif %}
    </ul>
    <form
      class="form-inline my-2 my-lg-0"
      method="GET"
      action="{% url 'products:list' %}"
    >
      <input
        name="term"
        value="{{ request.GET.term }}"
        class="form-control mr-sm-2"
        type="search"
        placeholder="Busca"
        aria-label="Busca"
      />
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">
        Busca
      </button>
    </form>
  </div>
</nav>

templates/partials/_pagination.html
{% if is_paginated %}
<div class="pagination">
  <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
            >&lsaquo;</a
        >
        </li>
        {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
        <a class="page-link" href="?page={{ num }}&term={{ request.GET.term }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item">
        <a class="page-link" href="?page={{ num }}&term={{ request.GET.term }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}&term={{ request.GET.term }}"
            >&rsaquo;</a
        >
        </li>
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&term={{ request.GET.term }}"
            >&raquo;</a
        >
        </li>
    {% endif %}
  </ul>
</div>
{% endif %}