orders/urls.py
from django.urls import path

from orders.views import OrderCreate, OrderDetail, OrderList, OrderPay

app_name = 'orders'

urlpatterns = [
    path('', OrderCreate.as_view(), name='create'),
    path('pay/<int:order_id>/', OrderPay.as_view(), name='pay'),
    path('detail/<int:order_id>/', OrderDetail.as_view(), name='detail'),
    path('list/', OrderList.as_view(), name='list'),
]

products/urls.py
from django.urls import path

from products.views import (ProductCart, ProductCartAdd, ProductCartRemove,
                            ProductCartResume, ProductDetail, ProductList)

app_name = 'products'

urlpatterns = [
    path('', ProductList.as_view(), name='list'),
    path('<slug>', ProductDetail.as_view(), name='detail'),
    path('cart/', ProductCart.as_view(), name='cart'),
    path('cart/add/', ProductCartAdd.as_view(), name='cart-add'),
    path('cart/remove/', ProductCartRemove.as_view(), name='cart-remove'),
    path('cart/resume/', ProductCartResume.as_view(), name='cart-resume'),
]

profiles/urls.py
from django.urls import path

from profiles.views import ProfileCreate, ProfileLogin, ProfileLogout

app_name = 'profiles'

urlpatterns = [
    path('', ProfileCreate.as_view(), name='create'),
    path('login/', ProfileLogin.as_view(), name='login'),
    path('logout/', ProfileLogout.as_view(), name='logout'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # keep admin first
    path('admin/', admin.site.urls),

    # other apps
    path('', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
import os

from django.conf import settings
from django.db import models
from PIL import Image


class Product(models.Model):
    name = models.CharField(max_length=80)
    description_short = models.TextField(max_length=150)
    description_long = models.TextField(max_length=350)
    image = models.ImageField(upload_to='products', blank=True, null=True)
    slug = models.SlugField(max_length=80, unique=True)
    price = models.FloatField()
    price_promo = models.FloatField(default=0)
    type = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variation'),
            ('N', 'Simple')
        )
    )

    def resize_image(self, width=800):
        image_path = os.path.join(settings.MEDIA_ROOT, self.image.name)
        img = Image.open(image_path)
        img_width, img_height = img.size

        if img_width <= width:
            img.close()
            return

        new_width = width
        new_height = round((new_width * img_height) / img_width)

        new_img = img.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(image_path, optimize=True, quality=50)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            self.resize_image()

    def __str__(self):
        return str(self.name)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    price = models.FloatField()
    price_promo = models.FloatField(default=0)
    stock = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return f'{self.product.name} - {self.name}'

products/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from products.models import Product, Variation


class MoneyMixin():
    def get_price(self):
        return self.to_money(self.price)

    def get_price_promo(self):
        return self.to_money(self.price_promo)

    def to_money(self, money):
        return f'R$ {money:,.2f}'


class ProductList(ListView):
    model = Product
    template_name = 'product_list.html'
    context_object_name = 'products'
    paginate_by = 1

    def get_queryset(self, *args, **kwargs):
        term = self.request.GET.get('term')
        qs = super().get_queryset(*args, **kwargs)

        if term:
            qs = qs.filter(
                Q(name__icontains=term) | Q(description_short__icontains=term) | Q(description_long__icontains=term)
            )
        return qs


class ProductDetail(DetailView, MoneyMixin):
    model = Product
    template_name = 'product_detail.html'
    context_object_name = 'product'
    slug_url_kwargs = 'slug'


class CartMixin(MoneyMixin):
    def get_cart_calc(self, cart={}):
        products = []
        cart_total_price = 0
        cart_total_itens = 0

        for product in cart.values():
            if isinstance(product, dict):
                cart_total_price += product['total_promo'] if product['total_promo'] else product['total']
                cart_total_itens += product['quantity']
                product_view = {
                    **product,
                    'price': self.to_money(product['total']),
                    'total': self.to_money(product['total']),
                    'total_promo': self.to_money(product['total_promo']) if product['total_promo'] > 0 else None,
                    'price_promo': self.to_money(product['price_promo']) if product['price_promo'] > 0 else None,
                }

                products.append(product_view)

        return [products, cart_total_price, cart_total_itens]


class ProductCart(View, CartMixin):
    def get(self, *args, **kwargs):
        cart = self.request.session.get('cart', {})
        products, cart_total_price, _ = self.get_cart_calc(cart)

        return render(self.request, 'product_cart.html', {
            'products': products,
            'cart_total_price': self.to_money(cart_total_price)
        })


class ProductCartAdd(View):
    def get(self, *args, **kwargs):
        referer = self.request.META.get('HTTP_REFERER', reverse('products:list'))

        variation = self.__get_variation()

        if not variation:
            return redirect(referer)

        in_stock = self.has_stock(variation)

        if in_stock:
            self.__add_to_cart(variation)

        return redirect(referer)

    def has_stock(self, variation: Variation, quantity=1):
        if variation.stock < quantity:
            messages.error(self.request, 'Estoque insuficiente.')
            return False
        return True

    def __add_to_cart(self, variation):
        var_id = str(variation.id)
        cart = self.__get_cart()
        variation = self.__get_variation()

        if var_id in cart:
            quantity = cart[var_id]['quantity'] + 1

            in_stock = self.has_stock(variation, quantity)

            if in_stock:
                cart[var_id]['quantity'] = quantity
                cart[var_id]['total'] = quantity * variation.price
                cart[var_id]['total_promo'] = quantity * variation.price_promo
            else:
                return
        else:
            cart[var_id] = {
                "id": var_id,
                'quantity': 1,
                'price': variation.price,
                'total': variation.price,
                'price_promo': variation.price_promo,
                'total_promo': variation.price_promo,
                'name': variation.product.name,
                'variation': variation.name,
                'slug': variation.product.slug,
                'image': variation.product.image.url,
            }

        cart['total'] += 1
        self.request.session.save()
        messages.success(self.request, 'Produto adicionado ao carrinho.')

    def __get_variation(self) -> Variation:
        var_id = self.request.GET.get('vid')

        if not var_id:
            messages.error(self.request, 'Produto não encontrado.')
            return None

        variation = Variation.objects.get(id=var_id)

        if not variation:
            messages.error(self.request, 'Produto não encontrado.')
            return None

        return variation

    def __get_cart(self):
        if not self.request.session.get('cart'):
            self.request.session['cart'] = {'total': 0}

        return self.request.session.get('cart')


class ProductCartRemove(View):
    def get(self, *args, **kwargs):
        cart = self.request.session.get('cart')
        referer = self.request.META.get('HTTP_REFERER', reverse('products:cart'))
        var_id = self.request.GET.get('vid')

        if not var_id or not cart or not cart[var_id]:
            return redirect(referer)

        variation = cart[var_id]
        cart['total'] -= variation['quantity']
        del cart[var_id]
        self.request.session.save()
        return redirect(referer)


class ProductCartResume(View, CartMixin):
    def get(self, *args, **kwargs):
        cart = self.request.session.get('cart', {})
        products, cart_total_price, _ = self.get_cart_calc(cart)

        profile = self.request.user.profile.first()
        if not profile:
            messages.warning(self.request, 'Você precisa de um perfil para continuar a compra.')
            return redirect('profiles:create')

        address = profile.address.first()
        if not address:
            messages.warning(self.request, 'Você precisa de um endereço para continuar a compra.')
            return redirect('profiles:create')

        return render(self.request, 'product_cart_resume.html', {
            'user': self.request.user,
            'profile': profile,
            'address': address,
            'products': products,
            'cart_total_price': self.to_money(cart_total_price)
        })

products/templates/product_cart.html
{% extends "base.html" %} {% block content %}
<div class="row mt-3">
  <div class="col">
    <h3>Carrinho de compras</h3>

    {% if products %}
    <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

    {% include "partials/_cart.html" %}
  </div>
</div>

<div class="row mt-3">
  <div class="col-lg">
    <p class="lead">Total no carrinho</p>

    <div class="table-responsive">
      <table class="table">
        <tr>
          <td class="font-weight-bold">Total</td>
          <td>{{ cart_total_price }}</td>
        </tr>
      </table>
    </div>
  </div>
  <div class="col-lg mt-auto">
    {% if request.user.is_authenticated %}
    <a class="btn btn-lg btn-block btn-primary" href="{% url "products:cart-resume" %}">
      Finalizar a compra
    </a>
    {% else %}
    <a class="btn btn-lg btn-block btn-primary" href="{% url "profiles:create" %}">
     Fazer login e comprar
    </a>
    {% endif %}

    {% else %}
    <p class="lead">Seu carrinho está vazio.</p>
    {% endif %}
  </div>
</div>
{% endblock content %}

products/templates/product_cart_resume.html
{% extends "base.html" %} {% block content %}
<div class="row mb-5">
  <div class="col-lg">
    <h2>Resumo da sua compra</h2>

    <p class="lead">Dados do usuário</p>
    <p>
      Caso precise editar, <a href="{% url 'profiles:create' %}">clique aqui</a>
    </p>
    <dl class="row">
      <dt class="col-lg-2">Nome:</dt>
      <dd class="col-lg-4">{{ user.first_name }}</dd>
      <dt class="col-lg-2">Sobrenome:</dt>
      <dd class="col-lg-4">{{ user.last_name }}</dd>

      <dt class="col-lg-2">Idade:</dt>
      <dd class="col-lg-4">{{ profile.age }}</dd>
      <dt class="col-lg-2">Nascimento:</dt>
      <dd class="col-lg-4">{{ profile.birth_date }}</dd>

      <dt class="col-lg-2">CPF:</dt>
      <dd class="col-lg-4">{{ profile.document }}</dd>
      <dt class="col-lg-2">E-mail:</dt>
      <dd class="col-lg-4">{{ user.email }}</dd>
    </dl>

    <p class="lead">Dados de endereço</p>
    <p>
      Caso precise editar, <a href="{% url 'profiles:create' %}">clique aqui</a>
    </p>
    <dl class="row">
      <dt class="col-lg-2">Endereço:</dt>
      <dd class="col-lg-4">{{ address.address }}</dd>
      <dt class="col-lg-2">Número:</dt>
      <dd class="col-lg-4">{{ address.number }}</dd>

      <dt class="col-lg-2">Bairro:</dt>
      <dd class="col-lg-4">{{ address.neighborhood }}</dd>

      <dt class="col-lg-2">Cidade:</dt>
      <dd class="col-lg-4">{{ address.city }}</dd>
      <dt class="col-lg-2">Estado:</dt>
      <dd class="col-lg-4">{{ address.state }}</dd>

      <dt class="col-lg-2">CEP:</dt>
      <dd class="col-lg-4">{{ address.code }}</dd>
    </dl>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <h3>Resumo do carrinho</h3>
    <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

    {% include 'partials/_cart.html' %}
  </div>
</div>
<div class="row mt-3">
  <div class="col">
    <p class="lead text-center">
      <span class="font-weight-bold">Total do carrinho:</span>
      {{ cart_total_price }}
    </p>
  </div>
</div>

<div class="row">
  <div class="col">
    <a class="btn btn-lg btn-block btn-primary" href="{% url "orders:create" %}"
      >Realizar pedido e pagar</a
    >
  </div>
</div>

{% endblock content %}

products/templates/product_detail.html
{% extends "base.html" %} {% block content %}
<div class="row">
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg">
        <div class="row no-gutters">
          <div class="col-lg-12">
            {% if product.image.url %}
            <img class="img-fluid" src="{{ product.image.url }}" />
            {% endif %}
          </div>
        </div>
      </div>

      <div class="col-lg">
        <div class="mt-4 mt-lg-0">
          <h1 class="h2">{{ product.name }}</h1>
          <p class="lead">{{ product.description_short }}</p>
          <p class="lead">
            {% if product.price_promo %}
            <span id="variation-preco-promocional" class="lead product-price">
              {{ product.get_price_promo }}
            </span>
            <span
              id="variation-preco"
              class="lead product-old-price text-muted">
              {{ product.get_price }}
            </span>
            {% else %}
            <span id="variation-preco" class="lead product-price">
              {{ product.get_price }}
            </span>
            {% endif %}
          </p>

          <form action="{% url "products:cart-add" %}" id="form-add-to-cart">
            <div class="form-group">
              {% if product.type == 'V' %}
                <select
                  id="select-variacoes"
                  name="vid"
                  class="form-control form-control-lg"
                >
                  {% for v in product.variation_set.all %}
                    <option
                      data-preco="{{ v.get_price }}"
                      data-preco-promocional="{{ v.get_price_promo }}"
                      value={{ v.id }}
                      >
                        {{ v.name }}
                    </option>
                  {% endfor %}
                </select>
              {% endif %}
          </div>

            <div class="text-left">
              <button type="submit" class="btn btn-primary btn-lg btn-block">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                Adicionar ao carrinho
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="mt-5 mb-5">
          <h2 class="text-center">{{ product.name }}</h2>
          {{ product.description_long | safe }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

products/templates/product_list.html
{% extends "base.html" %} {% block content %}
<div class="row">
  <div class="col-lg-12">
    <div class="card-columns">
      {% for product in products %}
      <div class="card">
        {% if product.image %}
        <a href="{% url 'products:detail' product.slug %}">
          <img
            class="card-img-top"
            src="{{ product.image.url }}"
            alt="{{ product.name }}"
          />
        </a>
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ product.name }}</h5>
          <p class="card-text">{{ product.description_short }}</p>
          <div class="container product-price-block text-center">
            {% if product.price_promo %}
            <span class="product-price">{{ product.get_price_promo }}</span>
            <span class="product-old-price text-muted"
              >{{ product.get_price }}</span
            >
            {% else %}
            <span class="product-price">{{ product.get_price }}</span>
            {% endif %}
          </div>
        </div>
        <div
          class="card-footer bg-transparent border-top-light-custom text-center"
        >
          <a
            href="{% url 'products:detail' product.slug %}"
            class="btn btn-primary btn-sm m-1 btn-block"
          >
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            Comprar
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}